<a href="https://colab.research.google.com/github/Purushgv/Basic_1/blob/main/PYTHON_BASICS_SEP4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x=2

In [ ]:
import math

In [ ]:
math.sqrt(4)

2.0

In [ ]:
round(12345.89621)

12346

In [ ]:
3>10

False

In [ ]:
7<25

True

In [ ]:
10==20

False

In [ ]:
10==10

True

In [ ]:
2+2

4

In [ ]:
9-5

4

In [ ]:
2*3

6

In [ ]:
25/5

5.0

In [ ]:
5==5

True

In [ ]:
15<20

True

In [ ]:
5|2

7

In [ ]:
5&2

0

In [ ]:
not(6==6)

False

In [ ]:
(10>20)&(20>10)

False

In [ ]:
(10>20)|(20>10)

True

In [ ]:
a=5>2

In [ ]:
print(a)

True


In [ ]:
b=10>50

In [ ]:
print(b)

False


In [ ]:
round(12345.562,0)

12346.0

In [ ]:
i=0
while i<=5:
  print(i)
  i=i+1

0
1
2
3
4
5


In [ ]:
i=0
while i<=5:
  print(i)
  i=i+1
print("Loop Ends")

0
1
2
3
4
5
Loop Ends


In [ ]:
i=0
while i<=5:
  print(i)
  i=i+1
print("Loop Ends")

0
1
2
3
4
5
Loop Ends


In [ ]:
i=10
while i<=5:
  print(i)
  i=i+1
print("Loop Ends")

Loop Ends


In [ ]:
range(6)

range(0, 6)

In [ ]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [ ]:
for i in range(6):
  print("Hello world")

Hello world
Hello world
Hello world
Hello world
Hello world
Hello world


In [ ]:
import numpy as np
from numpy.random import randn

In [ ]:
result= None
x=randn()
if x>1:
  result= "greater than 1"
print(x)
print(result) 

1.2343498132181299
greater than 1


In [ ]:
x=randn()
if x>1:
  result= "greater than 1"
print(x)
print(result) 

0.5447229424323988
greater than 1


In [ ]:
result= None
x=randn()
if x>1:
  result= "greater than 1"
else:
  result = "less than 1"
print(x)
print(result)

-0.5286733400314071
less than 1


In [ ]:
## chained if statement
result= None
x=randn()
if x>1:
  result= "greater than 1"
elif x<=-1:
  result = "less than -1"
else:
  result = "Between -1 and 1"
print(x)
print(result)

-0.7157685432219989
Between -1 and 1


In [ ]:
#Create a LIST

list1 = [1,2,3,4,5, 'abc',"Good",20.23, True ]

In [ ]:
type(list1)

list

In [ ]:
list1

[1, 2, 3, 4, 5, 'abc', 'Good', 20.23]

In [ ]:
# Indexing in python is always stars from "ZERO"

In [ ]:
list1[0]

1

In [ ]:
list1[5]

'abc'

In [ ]:
list1[2] = 'Great time teaching'

In [ ]:
list1

[1, 2, 'Great time teaching', 4, 5, 'abc', 'Good', 20.23]

In [ ]:
## Getting Date from list / Slicing

In [ ]:
list1[2:5]

['Great time teaching', 4, 5]

In [ ]:
##list[starting index:ending index +1]

In [ ]:
list1[::2]

[1, 'Great time teaching', 5, 'Good']

In [ ]:
list1[::-1]

[20.23, 'Good', 'abc', 5, 4, 'Great time teaching', 2, 1]

In [ ]:
tuple1= (10,'abc', 35.23)

In [ ]:
tuple1[1]

'abc'

In [ ]:
range(10)

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
print('hello world')

hello world


In [ ]:
x = (1,2,3,4,5,6)
len(x)

6

In [ ]:
x= 'z'
type(x)

str

In [ ]:
x=125
type(x)

int

In [ ]:
a=(1,2,5,0,12)
max(a)

12

In [ ]:
min(a)

0

In [ ]:
## ARRAYS 


import numpy as np

In [ ]:
a = np.array(list1)
print(a)

['1' '2' 'Great time teaching' '4' '5' 'abc' 'Good' '20.23']


In [ ]:
a

array(['1', '2', 'Great time teaching', '4', '5', 'abc', 'Good', '20.23'],
      dtype='<U32')

In [ ]:
##SLICING in Array

b = np.array([2345,6789,9876,1456,-1234])

In [ ]:
b.mean()

3846.4

In [ ]:
b

array([ 2345,  6789,  9876,  1456, -1234])

In [ ]:
b[::2]

array([ 2345,  9876, -1234])

In [ ]:
b[1::2]

array([6789, 1456])

In [ ]:
c = b[2:4]

In [ ]:
c

array([9876, 1456])

In [ ]:
c[:] = 222

In [ ]:
c

array([222, 222])

In [ ]:
b

array([ 2345,  6789,   222,   222, -1234])